export const CHANGE_TAB = 'CHANGE_TAB'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REFRESH_TOPICS_LIST = 'REFRESH_TOPICS_LIST'
export const LOAD_MORE_TOPICS = 'LOAD_MORE_TOPICS'
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE'
export const ROUTER_CHANGE = 'ROUTER_CHANGE'
export const FETCH_TOPIC_DATA = 'FETCH_TOPIC_DATA'

